# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0002_auto_20160328_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempedido',
            old_name='quandidade',
            new_name='quantidade',
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido', to='lojas.Pedido'),
        ),
    ]
