# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 02:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lojas', '0005_auto_20160329_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='carrinho', to=settings.AUTH_USER_MODEL),
        ),
    ]
